In [2]:
import numpy as np
# 列表形式
points = [[0, -1.8, 5], [100, -1.8, 5]]
print(type(points))  # <class 'list'>
print(points[0])     # [0, -1.8, 5]
print(points[0][0])  # 0

# NumPy数组形式
points_array = np.array(points)
print(type(points_array))  # <class 'numpy.ndarray'>
print(points_array[0])     # [ 0.  -1.8  5. ]
print(points_array[0,0])   # 0.0

<class 'list'>
[0, -1.8, 5]
0
<class 'numpy.ndarray'>
[ 0.  -1.8  5. ]
0.0


In [3]:
x_coords_array = points[:,0]  # 获取所有x坐标

TypeError: list indices must be integers or slices, not tuple

In [ ]:
import os


In [4]:
workpiece = "thickboard.pcd"
if not os.path.exists("./images/" + workpiece):
    os.makedirs('./images/' + workpiece )

In [28]:
import copy
a = 1
b = copy.deepcopy(a)
b

1

In [29]:
a = 2
b

1

In [ ]:
a = [1, 2, 3]
b = list(a)
b = a[:]

b = a.copy()
b = copy.copy(a)

# b = a
print(b)  # [1, 2, 3]
a.append(4)
print(b)  # [1, 2, 3, 4]

[1, 2, 3]
[1, 2, 3]


In [ ]:
a = 10
print(id(a)) # 140725807293640
a = 20
print(id(a)) # 140725807293960


140725807293640
140725807293960


In [31]:
def demonstrate_access_methods():
    # 创建数据
    points = np.array([[0,0,0], [1,1,1]], dtype=np.float64)
    pcd = o3d.geometry.PointCloud()
    pcd.points = o3d.utility.Vector3dVector(points)
    
    # 不同的访问方式
    array1 = np.asarray(pcd.points)        # 共享内存
    array2 = np.array(pcd.points)          # 创建新副本
    array3 = np.asarray(pcd.points).copy() # 显式创建副本
    
    # 修改测试
    array1[0,0] = 999
    array2[0,0] = 888
    array3[0,0] = 777
    
    print("修改后:")
    print("pcd.points:", np.asarray(pcd.points))
    print("array1:", array1)
    print("array2:", array2)
    print("array3:", array3)

demonstrate_access_methods()

修改后:
pcd.points: [[999.   0.   0.]
 [  1.   1.   1.]]
array1: [[999.   0.   0.]
 [  1.   1.   1.]]
array2: [[888.   0.   0.]
 [  1.   1.   1.]]
array3: [[777.   0.   0.]
 [  1.   1.   1.]]
